version: '3.8'

services:
  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nodejs

  nodejs:
    image: node:alpine
    volumes:
      - ./app:/app
    working_dir: /app
    command: sh -c "npm install && npm start"
    environment:
      - DB_HOST=mysql
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'my_database'
      MYSQL_PASSWORD: 'root'
      MYSQL_ROOT_PASSWORD: 'root'
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-scripts:/docker-entrypoint-initdb.d    
    ports:
      - "3308:3306"

volumes:
  mysql_data:
